<?xml version="1.0" encoding="utf-8"?><Database Name="Animals" Class="ConexionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-CCETU25\SQLEXPRESS;Initial Catalog=Animals;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Logica_app_Mascotas.Properties.Settings" SettingsPropertyName="AnimalsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_USUARIO" Member="TB_USUARIO">
    <Type Name="TB_USUARIO">
      <Column Name="ID_USUARIO" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="APELLIDOS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA_REGISTRO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NUMERO_VERIFICACION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TB_USUARIO_TB_SESION" Member="TB_SESION" ThisKey="ID_USUARIO" OtherKey="USUARIO" Type="TB_SESION" />
    </Type>
  </Table>
  <Table Name="dbo.TB_SESION" Member="TB_SESION">
    <Type Name="TB_SESION">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SESION" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="USUARIO" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ORIGEN" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FECHA_INICIO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHA_FINAL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FECHA_ACTUALIZACION" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TB_USUARIO_TB_SESION" Member="TB_USUARIO" ThisKey="USUARIO" OtherKey="ID_USUARIO" Type="TB_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_INSERTAR_USUARIO" Method="SP_INSERTAR_USUARIO1">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDOS" Parameter="aPELLIDOS" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NUMEROVERIFICACION" Parameter="nUMEROVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LOGIN" Method="SP_LOGIN">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="estado" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Parameter Name="apellidos" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>